# TensorFlow Basics

In [1]:
import tensorflow as tf

/Users/johnleonard/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
print(tf.__version__)

1.11.0


In [3]:
hello = tf.constant("Hello ")

In [4]:
world = tf.constant("World")

In [5]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [6]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [7]:
with tf.Session() as sess:
    result = sess.run(hello+world)

print(result)

b'Hello World'


In [8]:
a = tf.constant(10)
b = tf.constant(20)

type(a)

tensorflow.python.framework.ops.Tensor

In [9]:
a+b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [10]:
a+b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [13]:
with tf.Session() as sess:
    result = sess.run(a+b)
    
result

30

In [16]:
const = tf.constant(10)
fill_mat = tf.fill((4,4),10)
myzeros = tf.zeros((4,4))
myones = tf.ones((4,4))
myrandn = tf.random_normal((4,4),mean=0,stddev=1.0)
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [18]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

In [19]:
sess = tf.InteractiveSession()

In [22]:
for op in my_ops:
    print(sess.run(op))
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 0.02091338  0.4621785   0.26583323  0.5875651 ]
 [ 1.025075   -0.28874004  0.35473344  0.23682433]
 [ 0.5790766   1.2781961   0.19882283  0.92727464]
 [-1.5973693   0.21593483 -1.0493495   1.3333843 ]]


[[0.84445274 0.18208694 0.66748095 0.5100074 ]
 [0.56022227 0.9851489  0.7051518  0.96053565]
 [0.5900583  0.06714964 0.26938474 0.2344501 ]
 [0.7280792  0.4497286  0.51462305 0.97490716]]




In [23]:
a = tf.constant([[1,2],[3,4]])

In [24]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [25]:
b = tf.constant([[10],[100]])

In [26]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [27]:
result = tf.matmul(a,b)

In [28]:
sess.run(result)

array([[210],
       [430]], dtype=int32)